version: '3.9'
services: 
  dbpg: 
    container_name: 'dbpg'
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - custom

networks:
  custom:
    driver: bridge